### Import Tools

In [1]:
import numpy as np
import pandas as pd

### Load Data from External File

In [2]:
df = pd.read_csv("train.csv")

In [3]:
df

,id,age,education-num,capital-gain,capital-loss,hours-per-week,workclass_ Federal-gov,workclass_ Local-gov,workclass_ Private,workclass_ Self-emp-inc,...,native-country_ Scotland,native-country_ South,native-country_ Taiwan,native-country_ Thailand,native-country_ Trinadad&Tobago,native-country_ United-States,native-country_ Vietnam,native-country_ Yugoslavia,sex,income
0,0,0.136986,0.533333,0.00000,0.659121,0.397959,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0
1,1,0.356164,0.533333,0.00000,0.000000,0.397959,0,0,1,0,...,0,0,0,0,0,1,0,0,1,0
2,2,0.068493,0.533333,0.00000,0.000000,0.397959,0,0,1,0,...,0,0,0,0,0,1,0,0,1,0
3,3,0.136986,0.533333,0.00000,0.000000,0.377551,0,0,0,1,...,0,0,0,0,0,1,0,0,0,0
4,4,0.424658,0.733333,0.00000,0.000000,0.500000,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,7995,0.561644,0.533333,0.00000,0.000000,0.193878,0,0,1,0,...,0,0,0,0,0,1,0,0,0,1
7996,7996,0.383562,0.866667,0.01506,0.000000,0.448980,0,1,0,0,...,0,0,0,0,0,1,0,0,1,0
7997,7997,0.164384,0.733333,0.00000,0.000000,0.357143,0,0,1,0,...,0,0,0,0,0,1,0,0,1,0
7998,7998,0.383562,0.600000,0.00000,0.000000,0.397959,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0
7999,7999,0.260274,0.733333,0.00000,0.000000,0.346939,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0

### Get Data into numpy array

In [4]:
df0 = df

In [5]:
# Drop Label "income"
df0.drop(["income"],axis=1)

,id,age,education-num,capital-gain,capital-loss,hours-per-week,workclass_ Federal-gov,workclass_ Local-gov,workclass_ Private,workclass_ Self-emp-inc,...,native-country_ Puerto-Rico,native-country_ Scotland,native-country_ South,native-country_ Taiwan,native-country_ Thailand,native-country_ Trinadad&Tobago,native-country_ United-States,native-country_ Vietnam,native-country_ Yugoslavia,sex
0,0,0.136986,0.533333,0.00000,0.659121,0.397959,0,0,1,0,...,0,0,0,0,0,0,1,0,0,0
1,1,0.356164,0.533333,0.00000,0.000000,0.397959,0,0,1,0,...,0,0,0,0,0,0,1,0,0,1
2,2,0.068493,0.533333,0.00000,0.000000,0.397959,0,0,1,0,...,0,0,0,0,0,0,1,0,0,1
3,3,0.136986,0.533333,0.00000,0.000000,0.377551,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
4,4,0.424658,0.733333,0.00000,0.000000,0.500000,0,0,1,0,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,7995,0.561644,0.533333,0.00000,0.000000,0.193878,0,0,1,0,...,0,0,0,0,0,0,1,0,0,0
7996,7996,0.383562,0.866667,0.01506,0.000000,0.448980,0,1,0,0,...,0,0,0,0,0,0,1,0,0,1
7997,7997,0.164384,0.733333,0.00000,0.000000,0.357143,0,0,1,0,...,0,0,0,0,0,0,1,0,0,1
7998,7998,0.383562,0.600000,0.00000,0.000000,0.397959,0,0,1,0,...,0,0,0,0,0,0,1,0,0,0
7999,7999,0.260274,0.733333,0.00000,0.000000,0.346939,0,0,1,0,...,0,0,0,0,0,0,1,0,0,0

In [6]:
df.shape

(8000, 87)

In [7]:
df1 = df.iloc[:,[86]]

In [8]:
df1

      income
0          0
1          0
2          0
3          0
4          0
...      ...
7995       1
7996       0
7997       0
7998       0
7999       0

[8000 rows x 1 columns]

### Convert Pandas dataframes to numpy arrays

In [10]:
# convert df1 and df2 into numpy arrays
train_x = df0.to_numpy()
train_y = df1.to_numpy()

In [11]:
train_x.shape

(8000, 87)

In [12]:
train_y.shape

(8000, 1)

### Create all Functions We Need

In [13]:
# Euclidian distance
def euclidian_distance(row1, row2):
    distance = 0.0
    for i in range(len(row1) - 1):
        distance += (row1[i] - row2[i])**2
    return np.sqrt(distance)

In [14]:
def get_nearest_neighbors(example_set, query, k):
    distances = list()
    idx = 0
    for example_row in example_set:
        dist = euclidian_distance(query, example_row)
        distances.append((idx, example_row, dist))
        idx += 1;
    
    distances.sort(key=lambda tup: tup[2])
    neighbors_idx = list()
    for i in range(k):
        neighbors_idx.append(distances[i][0])
    return neighbors_idx

In [15]:
def knn_classify_point(examples_X, examples_y, query, k):
    # get the kNN list base on k
    #print("knn_classify_point(examples_X) shape", examples_X.shape)
    #print("knn_classify_point(examples_y) shape", examples_y.shape)
    #print("knn_classify_point(query) shape", query.shape)
    neighbors = get_nearest_neighbors(examples_X, query, k)
    # print(neighbors)
    # print(examples_y)
    
    # put the output train example_y in this
    output_nearest_neighbors = []
    # output_nearest_neighbors = []
       
    # get the output of nearest neighbors based on k value
    # NEED FURTHER DEBUGGING
    for neighbor_idx in neighbors:
        output_nearest_neighbors.append(examples_y[neighbor_idx][0])
    
    # output_nearest_neighbors = np.array(output_nearest_neighbors)
    #print(output_nearest_neighbors)
    # print(type(output_nearest_neighbors))
    
    
    # print("output_nearest_neighbors = ",output_nearest_neighbors)
    # get the maximum vote from the kNN output_nearest_neighbors
    predicted_label = max(set(output_nearest_neighbors), key=output_nearest_neighbors.count)
    
   
    return predicted_label

In [16]:
def predict(examples_X, examples_y, queries_X, k): 
    # For each query, run a knn classifier
    predicted_y = [knn_classify_point(examples_X, examples_y, query, k) for query in queries_X]
    return predicted_y

In [20]:
def cross_validation(train_X, train_y, num_folds, k):
    # Set some variables to use
    avg_val_acc = 0
    varr_val_acc = 0
    folds_container_X = []
    folds_container_y = []
    accuracy = []
    
    # Break data set into number of folds
    # and work on each fold
    for i in range(num_folds):
        folds_container_X.append(np.array_split(train_X, num_folds)[i])
        print("X", len(folds_container_X[i]))
        folds_container_y.append(np.array_split(train_y, num_folds)[i])
        print("y", len(folds_container_y[i]))
        queries = folds_container_X[i]
        
    # Get each data set into the fold_containers for train_X and train_y
    for i in range(num_folds):
        folds_container_X.append(np.array_split(train_X, num_folds)[i])
        print("X", len(folds_container_X[i]))
        folds_container_y.append(np.array_split(train_y, num_folds)[i])
        print("y", len(folds_container_y[i]))

    # looping Idea for i
    #     the train_X data has to coming from folds_container_X[not i]
    #     the train_y data has to coming from folds_container_y[not i]
    # if i == 0 then collect train data and label that greater than i
    # if i == num_folds-1 then collect train data and label from i = 0 to i-1 
    # if (i != 0) and (i < num_folds-1) then collect train data and label from i = 0 to i-1 and
    #                                      collect train data and label from i+1 to num_folds-2

    for i in range(num_folds):
        # For i == 0 then collect train data and label that greater than i
        if (i == 0):
            print("====================================", i)
            print("i == 0")
            queries = folds_container_X[i]
            print("queries of index ", i, " data rows = ",len(queries))
            # Stack data for train_fold_X into list
            print("Stack data for train_fold_X into list for ", i)
            train_fold_X = []
            train_fold_y = []
            p = i + 1
            for p in range(1,num_folds):
                for x in folds_container_X[p]:
                    train_fold_X.append(x)
                for y in folds_container_y[p]:
                    train_fold_y.append(y)
            print("Size of train_fold_X ", len(train_fold_X))
            # Convert train_fold_X list into numpy array
            train_fold_X = np.array(train_fold_X)
            print("Size of train_fold_y ", len(train_fold_y))
            # Convert train_fold_y list into numpy array
            train_fold_y = np.array(train_fold_y)
            # Call Prediction Function
            #k = 1
            pred3 = predict(train_fold_X, train_fold_y, queries, k)
            print("pred3 of index ", i, " data rows = ",len(pred3))
            # Compare Prediction to Actual 
            count = 0
            for v in range(len(pred3)):
                if (pred3[v] == folds_container_y[i][v]):
                    count +=1
            print("Correct Prediction = ", count)
            # Calculate Accuracy
            total = len(queries)
            print("Total = ", total)
            print("Count = ", count)
            print("Accuracy is Correct Prediction / Total = ", (count/total))
            accuracy.append((count/total))
            print(accuracy) 
    
        # for (i != 0) and (i < num_folds-1) then collect train data and label from i = 0 to i-1 and
        #                                        collect train data and label from i+1 to num_folds-2
        elif ((i != 0) and (i < num_folds-1)):
            print("====================================", i)
            print("(i != 0) and (i < num_folds-1)")
            queries = folds_container_X[i]
            print("queries of index ", i, " data rows = ",len(queries))
            # Stack data for train_fold_X into list
            print("Stack data for train_fold_X into list for ", i)
            train_fold_X = []
            train_fold_y = []
            p = 0
            for p in range(0,(num_folds-2)):
                for x in folds_container_X[p]:
                    train_fold_X.append(x)
                for y in folds_container_y[p]:
                    train_fold_y.append(y)
            print("Size of train_fold_X ", len(train_fold_X))
            # Convert train_fold_X list into numpy array
            train_fold_X = np.array(train_fold_X)
            print("Size of train_fold_y ", len(train_fold_y))
            # Convert train_fold_y list into numpy array
            train_fold_y = np.array(train_fold_y)
            # Call Prediction Function
            #k = 1
            pred3 = predict(train_fold_X, train_fold_y, queries, k)
            # Compare Prediction to Actual 
            count = 0
            for v in range(len(pred3)):
                if (pred3[v] == folds_container_y[i][v]):
                    count +=1
            print("Correct Prediction = ", count)
            # Calculate Accuracy
            total = len(queries)
            print("Total = ", total)
            print("Count = ", count)
            print("Accuracy is Correct Prediction / Total = ", (count/total))
            accuracy.append((count/total))
            print(accuracy)
        # For i == num_folds-1 then collect train data and label from i = 0 to i-1 
        elif (i == num_folds-1):
            print("====================================", i)
            print("i == num_folds-1 of ", i)
            queries = folds_container_X[i]
            print("queries of index ", i, " data rows = ",len(queries))
            # Stack data for train_fold_X into list
            print("Stack data for train_fold_X into list for ", i)
            train_fold_X = []
            train_fold_y = []
            p = 0
            for p in range(0,(num_folds-1)):
                for x in folds_container_X[p]:
                    train_fold_X.append(x)
                for y in folds_container_y[p]:
                    train_fold_y.append(y)
            print("Size of train_fold_X ", len(train_fold_X))
            # Convert train_fold_X list into numpy array
            train_fold_X = np.array(train_fold_X)
            print("Size of train_fold_y ", len(train_fold_y))
            # Convert train_fold_y list into numpy array
            train_fold_y = np.array(train_fold_y)
            # Call Prediction Function
            #k = 1
            pred3 = predict(train_fold_X, train_fold_y, queries, k)
            # Compare Prediction to Actual 
            count = 0
            for v in range(len(pred3)):
                if (pred3[v] == folds_container_y[i][v]):
                    count +=1
            print("Correct Prediction = ", count)
            # Calculate Accuracy
            total = len(queries)
            print("Total = ", total)
            print("Count = ", count)
            print("Accuracy is Correct Prediction / Total = ", (count/total))
            accuracy.append((count/total))
            print(accuracy)
    
    avg_val_acc = np.average(accuracy)
    varr_val_acc = np.var(accuracy)
    
    return avg_val_acc, varr_val_acc

In [18]:
num_folds=4
k=1
train_X = train_x
train_y = train_y
cross_validation(train_X, train_y, num_folds=4, k=1)

X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
==================================== 0
i == 0
queries of index  0  data rows =  2000
Stack data for train_fold_X into list for  0
Size of train_fold_X  6000
Size of train_fold_y  6000
pred3 of index  0  data rows =  2000
Correct Prediction =  1522
Total =  2000
Count =  1522
Accuracy is Correct Prediction / Total =  0.761
[0.761]
==================================== 1
(i != 0) and (i < num_folds-1)
queries of index  1  data rows =  2000
Stack data for train_fold_X into list for  1
Size of train_fold_X  4000
Size of train_fold_y  4000
Correct Prediction =  2000
Total =  2000
Count =  2000
Accuracy is Correct Prediction / Total =  1.0
[0.761, 1.0]
==================================== 2
(i != 0) and (i < num_folds-1)
queries of index  2  data rows =  2000
Stack data for train_fold_X into list for  2
Size of train_fold_X  4000
Size of train_fold_y  4000
Correct Prediction =  1491
Total =  2000
Count =  1491
Accuracy is Correct Prediction / Total =  0.7455
[0.761, 1.0, 0.7455]
==================================== 3
i == num_folds-1 of  3
queries of index  3  data rows =  2000
Stack data for train_fold_X into list for  3
Size of train_fold_X  6000
Size of train_fold_y  6000
Correct Prediction =  1509
Total =  2000
Count =  1509
Accuracy is Correct Prediction / Total =  0.7545
[0.761, 1.0, 0.7455, 0.7545]

(0.81525, 0.0114078125)

In [21]:
num_folds=4
k=3
train_X = train_x
train_y = train_y
cross_validation(train_X, train_y, num_folds, k)

X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
==================================== 0
i == 0
queries of index  0  data rows =  2000
Stack data for train_fold_X into list for  0
Size of train_fold_X  6000
Size of train_fold_y  6000
pred3 of index  0  data rows =  2000
Correct Prediction =  1522
Total =  2000
Count =  1522
Accuracy is Correct Prediction / Total =  0.761
[0.761]
==================================== 1
(i != 0) and (i < num_folds-1)
queries of index  1  data rows =  2000
Stack data for train_fold_X into list for  1
Size of train_fold_X  4000
Size of train_fold_y  4000
Correct Prediction =  1676
Total =  2000
Count =  1676
Accuracy is Correct Prediction / Total =  0.838
[0.761, 0.838]
==================================== 2
(i != 0) and (i < num_folds-1)
queries of index  2  data rows =  2000
Stack data for train_fold_X into list for  2
Size of train_fold_X  4000
Size of train_fold_y  4000
Correct Prediction =  1491
Total =  2000
Count =  1491
Accuracy is Correct Prediction / Total =  0.7455
[0.761, 0.838, 0.7455]
==================================== 3
i == num_folds-1 of  3
queries of index  3  data rows =  2000
Stack data for train_fold_X into list for  3
Size of train_fold_X  6000
Size of train_fold_y  6000
Correct Prediction =  1509
Total =  2000
Count =  1509
Accuracy is Correct Prediction / Total =  0.7545
[0.761, 0.838, 0.7455, 0.7545]

(0.77475, 0.0013638124999999985)

In [22]:
num_folds=4
k=5
train_X = train_x
train_y = train_y
cross_validation(train_X, train_y, num_folds, k)

X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
==================================== 0
i == 0
queries of index  0  data rows =  2000
Stack data for train_fold_X into list for  0
Size of train_fold_X  6000
Size of train_fold_y  6000
pred3 of index  0  data rows =  2000
Correct Prediction =  1522
Total =  2000
Count =  1522
Accuracy is Correct Prediction / Total =  0.761
[0.761]
==================================== 1
(i != 0) and (i < num_folds-1)
queries of index  1  data rows =  2000
Stack data for train_fold_X into list for  1
Size of train_fold_X  4000
Size of train_fold_y  4000
Correct Prediction =  1559
Total =  2000
Count =  1559
Accuracy is Correct Prediction / Total =  0.7795
[0.761, 0.7795]
==================================== 2
(i != 0) and (i < num_folds-1)
queries of index  2  data rows =  2000
Stack data for train_fold_X into list for  2
Size of train_fold_X  4000
Size of train_fold_y  4000
Correct Prediction =  1491
Total =  2000
Count =  1491
Accuracy is Correct Prediction / Total =  0.7455
[0.761, 0.7795, 0.7455]
==================================== 3
i == num_folds-1 of  3
queries of index  3  data rows =  2000
Stack data for train_fold_X into list for  3
Size of train_fold_X  6000
Size of train_fold_y  6000
Correct Prediction =  1509
Total =  2000
Count =  1509
Accuracy is Correct Prediction / Total =  0.7545
[0.761, 0.7795, 0.7455, 0.7545]

(0.7601249999999999, 0.00015542187499999947)

In [23]:
num_folds=4
k=7
train_X = train_x
train_y = train_y
cross_validation(train_X, train_y, num_folds, k)

X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
==================================== 0
i == 0
queries of index  0  data rows =  2000
Stack data for train_fold_X into list for  0
Size of train_fold_X  6000
Size of train_fold_y  6000
pred3 of index  0  data rows =  2000
Correct Prediction =  1522
Total =  2000
Count =  1522
Accuracy is Correct Prediction / Total =  0.761
[0.761]
==================================== 1
(i != 0) and (i < num_folds-1)
queries of index  1  data rows =  2000
Stack data for train_fold_X into list for  1
Size of train_fold_X  4000
Size of train_fold_y  4000
Correct Prediction =  1527
Total =  2000
Count =  1527
Accuracy is Correct Prediction / Total =  0.7635
[0.761, 0.7635]
==================================== 2
(i != 0) and (i < num_folds-1)
queries of index  2  data rows =  2000
Stack data for train_fold_X into list for  2
Size of train_fold_X  4000
Size of train_fold_y  4000
Correct Prediction =  1491
Total =  2000
Count =  1491
Accuracy is Correct Prediction / Total =  0.7455
[0.761, 0.7635, 0.7455]
==================================== 3
i == num_folds-1 of  3
queries of index  3  data rows =  2000
Stack data for train_fold_X into list for  3
Size of train_fold_X  6000
Size of train_fold_y  6000
Correct Prediction =  1509
Total =  2000
Count =  1509
Accuracy is Correct Prediction / Total =  0.7545
[0.761, 0.7635, 0.7455, 0.7545]

(0.7561249999999999, 4.842187499999963e-05)

In [24]:
num_folds=4
k=9
train_X = train_x
train_y = train_y
cross_validation(train_X, train_y, num_folds, k)

X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
==================================== 0
i == 0
queries of index  0  data rows =  2000
Stack data for train_fold_X into list for  0
Size of train_fold_X  6000
Size of train_fold_y  6000
pred3 of index  0  data rows =  2000
Correct Prediction =  1522
Total =  2000
Count =  1522
Accuracy is Correct Prediction / Total =  0.761
[0.761]
==================================== 1
(i != 0) and (i < num_folds-1)
queries of index  1  data rows =  2000
Stack data for train_fold_X into list for  1
Size of train_fold_X  4000
Size of train_fold_y  4000
Correct Prediction =  1515
Total =  2000
Count =  1515
Accuracy is Correct Prediction / Total =  0.7575
[0.761, 0.7575]
==================================== 2
(i != 0) and (i < num_folds-1)
queries of index  2  data rows =  2000
Stack data for train_fold_X into list for  2
Size of train_fold_X  4000
Size of train_fold_y  4000
Correct Prediction =  1491
Total =  2000
Count =  1491
Accuracy is Correct Prediction / Total =  0.7455
[0.761, 0.7575, 0.7455]
==================================== 3
i == num_folds-1 of  3
queries of index  3  data rows =  2000
Stack data for train_fold_X into list for  3
Size of train_fold_X  6000
Size of train_fold_y  6000
Correct Prediction =  1509
Total =  2000
Count =  1509
Accuracy is Correct Prediction / Total =  0.7545
[0.761, 0.7575, 0.7455, 0.7545]

(0.7546250000000001, 3.304687499999973e-05)

In [25]:
num_folds=4
k=99
train_X = train_x
train_y = train_y
cross_validation(train_X, train_y, num_folds, k)

X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
==================================== 0
i == 0
queries of index  0  data rows =  2000
Stack data for train_fold_X into list for  0
Size of train_fold_X  6000
Size of train_fold_y  6000
pred3 of index  0  data rows =  2000
Correct Prediction =  1522
Total =  2000
Count =  1522
Accuracy is Correct Prediction / Total =  0.761
[0.761]
==================================== 1
(i != 0) and (i < num_folds-1)
queries of index  1  data rows =  2000
Stack data for train_fold_X into list for  1
Size of train_fold_X  4000
Size of train_fold_y  4000
Correct Prediction =  1511
Total =  2000
Count =  1511
Accuracy is Correct Prediction / Total =  0.7555
[0.761, 0.7555]
==================================== 2
(i != 0) and (i < num_folds-1)
queries of index  2  data rows =  2000
Stack data for train_fold_X into list for  2
Size of train_fold_X  4000
Size of train_fold_y  4000
Correct Prediction =  1491
Total =  2000
Count =  1491
Accuracy is Correct Prediction / Total =  0.7455
[0.761, 0.7555, 0.7455]
==================================== 3
i == num_folds-1 of  3
queries of index  3  data rows =  2000
Stack data for train_fold_X into list for  3
Size of train_fold_X  6000
Size of train_fold_y  6000
Correct Prediction =  1509
Total =  2000
Count =  1509
Accuracy is Correct Prediction / Total =  0.7545
[0.761, 0.7555, 0.7455, 0.7545]

(0.7541249999999999, 3.092187499999976e-05)

In [26]:
num_folds=4
k=999
train_X = train_x
train_y = train_y
cross_validation(train_X, train_y, num_folds, k)

X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
==================================== 0
i == 0
queries of index  0  data rows =  2000
Stack data for train_fold_X into list for  0
Size of train_fold_X  6000
Size of train_fold_y  6000
pred3 of index  0  data rows =  2000
Correct Prediction =  1522
Total =  2000
Count =  1522
Accuracy is Correct Prediction / Total =  0.761
[0.761]
==================================== 1
(i != 0) and (i < num_folds-1)
queries of index  1  data rows =  2000
Stack data for train_fold_X into list for  1
Size of train_fold_X  4000
Size of train_fold_y  4000
Correct Prediction =  1511
Total =  2000
Count =  1511
Accuracy is Correct Prediction / Total =  0.7555
[0.761, 0.7555]
==================================== 2
(i != 0) and (i < num_folds-1)
queries of index  2  data rows =  2000
Stack data for train_fold_X into list for  2
Size of train_fold_X  4000
Size of train_fold_y  4000
Correct Prediction =  1491
Total =  2000
Count =  1491
Accuracy is Correct Prediction / Total =  0.7455
[0.761, 0.7555, 0.7455]
==================================== 3
i == num_folds-1 of  3
queries of index  3  data rows =  2000
Stack data for train_fold_X into list for  3
Size of train_fold_X  6000
Size of train_fold_y  6000
Correct Prediction =  1509
Total =  2000
Count =  1509
Accuracy is Correct Prediction / Total =  0.7545
[0.761, 0.7555, 0.7455, 0.7545]

(0.7541249999999999, 3.092187499999976e-05)

In [27]:
num_folds=4
k=8000
train_X = train_x
train_y = train_y
cross_validation(train_X, train_y, num_folds, k)

X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
X 2000
y 2000
==================================== 0
i == 0
queries of index  0  data rows =  2000
Stack data for train_fold_X into list for  0
Size of train_fold_X  6000
Size of train_fold_y  6000

IndexError: list index out of range